## YAML Template.
---
version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
            - echo changing directoy to player-svc
            - cd player-svc
    build:
        commands:
            - echo Build started
            - mvn clean install
    post_build:
        commands:
            - echo Nothing to do in the post_build phase
    artifacts:
        files:
            - player-svc*.jar
        base_directory: 'player-svc/target'
        discard-paths: yes
        name: player-svc-$(date +%Y-%m-%d)-$AWS_REGION