## YAML Template.
---
version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
    pre_build:
        commands:
            - echo changing directoy to player-svc
            - cd player-svc
    build:
        commands:
            - echo Build started
            - mvn clean install
    post_build:
        commands:
            - cd ..
artifacts:
    files:
        - player-svc/target/player-svc-1.0.0-SNAPSHOT.jar    
    discard-paths: yes
    name: player-svc-$(date +%Y-%m-%d)-$AWS_REGION